{
 "title": "Dashboard proxima",
 "description": "Performance metrics for proxima",
 "tags": [ "proxima" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(fs_extensions_total, job)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(fs_extensions_total{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Busy",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(((count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$node\",job=\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))",
       "legendFormat": "Busy",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "Used RAM",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$node\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"})",
       "legendFormat": "Used",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "Transfered data volume",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"})*(9.31*10^-10)",
       "legendFormat": "Incoming ",
       "stepMode": "min"
      },
      {
       "expr": "sum(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"})*(9.31*10^-10)",
       "legendFormat": "Outgoing",
       "stepMode": "min"
      },
      {
       "expr": "(sum(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"})+sum(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}))*(9.31*10^-10)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bps", "label": "bits out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "node_load5{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "node_load15{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Load 15m"
      }
     ]
    }
   ]
  },
  { "title": "SIP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "SIP Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fs_uptime{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "SIP Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fs_status{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "UC Service Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ucservice_uptime{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Uptime",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "UC Service Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ucservice_status{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Status",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "SIP Profiles status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fs_sofia_status{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{profile}}"
    }
   ]
  },
  {
   "title": "SIP Registrations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "fs_extensions_total{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Total users"
    },
    {
     "expr": "fs_registrations_count{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Registrations"
    }
   ]
  },
  {
   "title": "SIP Gateway",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "fs_gateways_total{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "fs_gateways{instance=\"$node\",job=\"$job\",status=\"up\"}",
     "legendFormat": "Online"
    }
   ]
  },
  {
   "title": "SIP Calls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "fs_calls_count{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Calls"
    }
   ]
  },
  {
   "title": "SIP MOS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "fs_mos{instance=\"$node\",job=\"$job\",stat=\"min\"}",
     "legendFormat": "MOS min"
    },
    {
     "expr": "fs_mos{instance=\"$node\",job=\"$job\",stat=\"max\"}",
     "legendFormat": "MOS max"
    },
    {
     "expr": "fs_mos{instance=\"$node\",job=\"$job\",stat=\"avg\"}",
     "legendFormat": "MOS avg"
    }
   ]
  },
  {
   "title": "Maintenance mode",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nexiop_maintenance_mode{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Status",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Upgrade mode",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nexiop_upgrade_mode{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Status",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Chat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chat Uptime",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "chatservice_uptime{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Uptime",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "Chat Status",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chatservice_status{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Status",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "Connected chat clients",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
     "targets": [
      {
       "expr": "prosody_mod_c2s__connections{instance=\"$node\",job=\"$job\",type=\"c2s\",ip_family=\"ipv4\"}",
       "legendFormat": "Connections",
       "stepMode": "min"
      }
     ]
    }
   ]
  },
  {
   "title": "PHP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "PHP Uptime",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "phpfpm_start_since{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Uptime",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "PHP Status",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "phpfpm_status{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Status",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "PHP Process Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "phpfpm_active_processes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Active",
       "stepMode": "min"
      },
      {
       "expr": "phpfpm_idle_processes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Idle",
       "stepMode": "min"
      },
      {
       "expr": "phpfpm_total_processes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Total",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "PHP Scores",
     "type": "stat",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "phpfpm_accepted_connections{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Accepted Connections",
       "stepMode": "min"
      },
      {
       "expr": "phpfpm_max_active_processes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Max Active Processes",
       "stepMode": "min"
      },
      {
       "expr": "phpfpm_max_children_reached{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Max Children Reached",
       "stepMode": "min"
      },
      {
       "expr": "phpfpm_slow_requests{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Slow Requests",
       "stepMode": "min"
      },
      {
       "expr": "phpfpm_max_listen_queue{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Max Listen Queue",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "PHP Queue Pending Connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "phpfpm_listen_queue{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Requests in the queue",
       "stepMode": "min"
      }
     ]
    }
   ]
  },
  {
   "title": "NGINX",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "NGINX Status",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nginx_up{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Status",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "NGINX Total requests rate",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "irate(nginx_http_requests_total{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "Uptime",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "NGINX Processed connections rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(nginx_connections_accepted{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "Accepted",
       "stepMode": "min"
      },
      {
       "expr": "irate(nginx_connections_handled{instance=\"$node\",job=\"$job\"}[5m])",
       "legendFormat": "Handled",
       "stepMode": "min"
      }
     ]
    },
    {
     "title": "NGINX Active Connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nginx_connections_active{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Active",
       "stepMode": "min"
      },
      {
       "expr": "nginx_connections_reading{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Reading",
       "stepMode": "min"
      },
      {
       "expr": "nginx_connections_waiting{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Waiting",
       "stepMode": "min"
      },
      {
       "expr": "nginx_connections_writing{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Writing",
       "stepMode": "min"
      }
     ]
    }
   ]
  }
 ]
}