{
 "title": "Monitor ###LABEL###",
 "description": "Performance metrics for Proxima",
 "tags": [ "proxima" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "System Uptime - ###LABEL###",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"###FQDN###\",job=\"node\"} - node_boot_time_seconds{instance=\"###FQDN###\",job=\"node\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "SIP Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fs_uptime{instance=\"###FQDN###\",job=\"node\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "UC Service Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ucservice_uptime{instance=\"###FQDN###\",job=\"node\"}",
     "legendFormat": "Uptime",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Chat Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "chatservice_uptime{instance=\"###FQDN###\",job=\"node\"}",
     "legendFormat": "Uptime",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "SIP Registrations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fs_registrations_count{instance=\"###FQDN###\",job=\"node\"}",
     "legendFormat": "Registrations",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Chat Online",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "prosody_mod_c2s__connections{instance=\"###FQDN###\",job=\"node\",type=\"c2s\",ip_family=\"ipv4\"}",
     "legendFormat": "Online",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "SIP Calls",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fs_calls_count{instance=\"###FQDN###\",job=\"node\"}",
     "legendFormat": "Calls",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "SIP Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fs_status{instance=\"###FQDN###\",job=\"node\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "UC Service Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ucservice_status{instance=\"###FQDN###\",job=\"node\"}",
     "legendFormat": "Status",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Chat Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chatservice_status{instance=\"###FQDN###\",job=\"node\"}",
     "legendFormat": "Status",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Maintenance mode",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nexiop_maintenance_mode{instance=\"###FQDN###\",job=\"node\"}",
     "legendFormat": "Status",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Upgrade mode",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nexiop_upgrade_mode{instance=\"###FQDN###\",job=\"node\"}",
     "legendFormat": "Status",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "SIP Profiles status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fs_sofia_status{instance=\"###FQDN###\",job=\"node\"}",
     "legendFormat": "{{profile}}"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"###FQDN###\",job=\"node\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"###FQDN###\",job=\"node\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"###FQDN###\",job=\"node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"###FQDN###\",job=\"node\"} * 100) / node_memory_MemTotal_bytes{instance=\"###FQDN###\",job=\"node\"})"
    }
   ]
  },
  {
   "title": "SIP Extensions Online",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(fs_registrations_count{instance=\"###FQDN###\",job=\"node\"} / fs_extensions_total{instance=\"###FQDN###\",job=\"node\"}) * 100",
     "legendFormat": "Online"
    }
   ]
  },
  {
   "title": "SIP Gateways Online",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(fs_gateways{instance=\"###FQDN###\",job=\"node\",status=\"up\"}) / sum(fs_gateways_total{instance=\"###FQDN###\",job=\"node\"})) * 100",
     "legendFormat": "Online"
    }
   ]
  },
  {
   "title": "SIP MOS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "fs_mos{instance=\"###FQDN###\",job=\"node\",stat=\"min\"}",
     "legendFormat": "MOS min"
    },
    {
     "expr": "fs_mos{instance=\"###FQDN###\",job=\"node\",stat=\"max\"}",
     "legendFormat": "MOS max"
    },
    {
     "expr": "fs_mos{instance=\"###FQDN###\",job=\"node\",stat=\"avg\"}",
     "legendFormat": "MOS avg"
    }
   ]
  },
  {
   "title": "SIP Registrations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "fs_registrations_count{instance=\"###FQDN###\",job=\"node\"}",
     "legendFormat": "Registrations"
    },
    {
     "expr": "fs_extensions_total{instance=\"###FQDN###\",job=\"node\"}",
     "legendFormat": "Total users"
    }
   ]
  },
  {
   "title": "SIP Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "fs_gateways{instance=\"###FQDN###\",job=\"node\",status=\"up\"}",
     "legendFormat": "Online"
    },
    {
     "expr": "fs_gateways_total{instance=\"###FQDN###\",job=\"node\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "SIP Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "fs_calls_count{instance=\"###FQDN###\",job=\"node\"}",
     "legendFormat": "Calls"
    }
   ]
  }
 ]
}