{
 "title": "Call Center - ###LABEL###",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Chiamate in attesa",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cc_waiting_calls{pbx=\"###FQDN###\", extqueue=\"###EXTQUEUE###\"}",
     "legendFormat": "In attesa"
    }
   ]
  },
  {
   "title": "Chiamate in corso",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cc_active_calls{pbx=\"###FQDN###\", extqueue=\"###EXTQUEUE###\"}",
     "legendFormat": "In corso"
    }
   ]
  },
  {
   "title": "Perse ultime 24 ore",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(cc_missed_calls_total{pbx=\"###FQDN###\", extqueue=\"###EXTQUEUE###\"}[24h])",
     "legendFormat": "Perse"
    }
   ]
  },
  {
   "title": "Abbandonate ultime 24 ore",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(cc_abandoned_calls_total{pbx=\"###FQDN###\", extqueue=\"###EXTQUEUE###\"}[24h])",
     "legendFormat": "Abbandonate"
    }
   ]
  },
  {
   "title": "SLA",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cc_sla{pbx=\"###FQDN###\", extqueue=\"###EXTQUEUE###\"}",
     "legendFormat": "SLA"
    }
   ]
  },
  {
   "title": "Agenti Disponibili",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(cc_available_agents{pbx=\"###FQDN###\", extqueue=\"###EXTQUEUE###\"} / cc_total_agents{pbx=\"###FQDN###\", extqueue=\"###EXTQUEUE###\"}) * 100",
     "legendFormat": "Disponibili"
    }
   ]
  },
  {
   "title": "Agenti In Pausa",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(cc_on_break_agents{pbx=\"###FQDN###\", extqueue=\"###EXTQUEUE###\"} / cc_total_agents{pbx=\"###FQDN###\", extqueue=\"###EXTQUEUE###\"}) * 100",
     "legendFormat": "In pausa"
    }
   ]
  },
  {
   "title": "Risposte ultime 24 ore",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(cc_answered_calls_total{pbx=\"###FQDN###\", extqueue=\"###EXTQUEUE###\"}[24h])",
     "legendFormat": "Risposte"
    }
   ]
  },
  {
   "title": "Totali ultime 24 ore",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(cc_total_calls_total{pbx=\"###FQDN###\", extqueue=\"###EXTQUEUE###\"}[24h])",
     "legendFormat": "Ricevute"
    }
   ]
  },
  {
   "title": "% Risposte",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(cc_answered_calls_total{pbx=\"###FQDN###\", extqueue=\"###EXTQUEUE###\"} / cc_total_calls_total{pbx=\"###FQDN###\", extqueue=\"###EXTQUEUE###\"}) * 100",
     "legendFormat": "Risposte"
    }
   ]
  },
  {
   "title": "% Perse",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(cc_missed_calls_total{pbx=\"###FQDN###\", extqueue=\"###EXTQUEUE###\"} / cc_total_calls_total{pbx=\"###FQDN###\", extqueue=\"###EXTQUEUE###\"}) * 100",
     "legendFormat": "Perse"
    }
   ]
  },
  {
   "title": "% Abbandonate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(cc_abandoned_calls_total{pbx=\"###FQDN###\", extqueue=\"###EXTQUEUE###\"} / cc_total_calls_total{pbx=\"###FQDN###\", extqueue=\"###EXTQUEUE###\"}) * 100",
     "legendFormat": "Abbandonate"
    }
   ]
  },
  {
   "title": "Massimo tempo di attesa",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cc_max_waiting_time_all_calls{pbx=\"###FQDN###\", extqueue=\"###EXTQUEUE###\"}",
     "legendFormat": "Seconds"
    }
   ]
  },
  {
   "title": "Media tempo di attesa",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cc_avg_waiting_time_all_calls{pbx=\"###FQDN###\", extqueue=\"###EXTQUEUE###\"}",
     "legendFormat": "Seconds"
    }
   ]
  },
  {
   "title": "Media tempo di attesa risposte",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cc_avg_waiting_time_answered_calls{pbx=\"###FQDN###\", extqueue=\"###EXTQUEUE###\"}",
     "legendFormat": "Seconds"
    }
   ]
  },
  {
   "title": "Media tempo di abbandono",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cc_avg_abandoned_time{pbx=\"###FQDN###\", extqueue=\"###EXTQUEUE###\"}",
     "legendFormat": "Seconds"
    }
   ]
  },
  {
   "title": "Media tempo di conversazione",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cc_avg_talking_time{pbx=\"###FQDN###\", extqueue=\"###EXTQUEUE###\"}",
     "legendFormat": "Seconds"
    }
   ]
  }
 ]
}